### ISSUE TITLE
Problem with Gradle 8

### ISSUE THREAD

**Issue by rjaros** [mpetuska/npm-publish#110]
Hello, 
After migrating my project to Gradle 8.0.1 the build is failing with the following message:
```
Some problems were found with the configuration of task ':kvision-assets:publishKvisionAssetsPackageToNpmjsRegistry' (type 'NpmPublishTask').
  - Gradle detected a problem with the following location: '/opt/rjaros/.gradle/nodejs/node-v16.13.0-linux-x64/bin/node'.
    
    Reason: Task ':kvision-assets:publishKvisionAssetsPackageToNpmjsRegistry' uses this output of task ':kotlinNodeJsSetup' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':kotlinNodeJsSetup' as an input of ':kvision-assets:publishKvisionAssetsPackageToNpmjsRegistry'.
      2. Declare an explicit dependency on ':kotlinNodeJsSetup' from ':kvision-assets:publishKvisionAssetsPackageToNpmjsRegistry' using Task#dependsOn.
      3. Declare an explicit dependency on ':kotlinNodeJsSetup' from ':kvision-assets:publishKvisionAssetsPackageToNpmjsRegistry' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

**Comment by mpetuska** [comment]
Thanks. As a temporary workaround you could add the dependency to that task on consumer end.

**Comment by mpetuska** [comment]
e.g.
```
tasks.publishKvisionAssetsPackageToNpmjsRegistry.dependsOn("kotlinNodeJsSetup")
```

**Comment by mpetuska** [comment]
Apologies to both, I've totally forgot about this issue. I'll look into fixing both this weekend

**Comment by mpetuska** [comment]
Original `kotlinNodeJsSetup` is now resolved.

> Unrelated to the above but also related to Gradle 8 compatibility (at least with Gradle 8.1.1):
> 
> ![image](https://user-images.githubusercontent.com/8314616/234210631-580dd72f-bbfd-41f7-9b68-7cb5e9f8590f.png)
> 
> The `dependencies` function is now clashing with `Project.dependencies` from the Kotlin DSL. For now it seems to still compile, but it does show an error in the IDE. Doing something like the following fixes it (since thankfully the `Project.dependencies` argument has a different name):
> 
> ![image](https://user-images.githubusercontent.com/8314616/234210778-ded14006-8b24-4174-aec4-cb5b75c1d80c.png)
> 
> It might make sense to introduce an alias to `dependencies` such as `packageDependencies` and perhaps deprecate the former.
> 
> If I'm missing something obvious and there's a less hacky workaround please do let me know!
> 
> I tried going over the Gradle release notes to check if this change in behaviour is mentioned anywhere but couldn't find anything to reference. I'd appreciate if someone could find a reference as to why this is now happening.
> 
> Also, please let me know if you'd prefer that I create a new issue to track this.

The "propper" solution to this would be to simply specify an explicit receiver:
```kotlin
register {
  this.dependencies {
    ...
  }
}
```

In any case, these `dependencies` blocks inside `NpmPackage` and `PackageJson` blocks are provided as failsafes and should generally be avoided when kotlin plugin is present. Recommended way to manage dependencies is inside kotlin js sourceSet's dependencies block.

As for the "fix", I'll leave the DSL present as-is with updated KDoc to mention this gotcha. Additionally, I've added a new generic DSL to set any object property inside `packageJson` so you could so something like this in untyped manner:
```kotlin
packageJson {
  "dependencies" {
    "is-even": "*"
  }
}
```

**Comment by YarnSphere** [comment]
Thanks! In my case, one of the Gradle projects that I publish doesn't use Kotlin (it's a JS project which consumes a Kotlin multiplatform project and is in the same monorepo, so I use Gradle as the build tool for everything), meaning that I have to specify the dependencies of said project manually.

The "proper" workaround is good enough for me, please consider the issue closed. :)
