### ISSUE TITLE
Support specifying a distribution tag when publishing an npm package

### ISSUE THREAD

**Issue by frett** [mpetuska/npm-publish#115]
The npm publish command supports specifying a distribution tag when publishing. The distribution tag defaults to `latest` if no tag is specified. see: https://docs.npmjs.com/adding-dist-tags-to-packages

It would be nice if we could programmatically configure the tag to use within the gradle plugin. Or as an alternative provide a mechanism to specify additional arbitrary parameters to send to the npm action.

The current workaround is to manually manage distribution tags after you publish using the `npm dist-tag` action.

**Comment by mpetuska** [comment]
Sounds useful! I try to put some time aside to add it tgis weekend.
