### ISSUE TITLE
self-signed certificate

### ISSUE THREAD

**Issue by albert361** [mpetuska/npm-publish#128]
Hi, 

Thanks for developing this plugin!
Is there a way to bypass self-signed certificate error?

```
npm notice Publishing to https://xxxxxxxxxxx/
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
npm ERR! request to https://xxxxxxxxxxx/@my-org%2fmy-package failed, reason: self-signed certificate in certificate chain
```

**Comment by albert361** [comment]
Typically, we can use either:
1. `npm config set strict-ssl false` -> not good since it updates global `.npmrc`
2. `npm config set cafile /path/to/cert.pem` -> not good since it updates global `.npmrc`
3. `NODE_TLS_REJECT_UNAUTHORIZED=0 npm publish .....`
4. `npm publish --strict-ssl false .....`
IMO we should at least one of point 3 or 4 to let user temporary disable strict-ssl check ONLY for publishing.  
Regarding point 1 and 2, if update global `.npmrc` is Okay, then it should be configured already.

**Comment by mpetuska** [comment]
Gotcha. Opt 4 is definitely something I could add to the plugin, but for now I think you can use opt 3 by passing that env var to gradle 

e.g. NODE_TLS_REJECT_UNAUTHORIZED=0 ./gradlew publish

**Comment by mpetuska** [comment]
@albert361 can you share where that `--strict-ssl` option is documented? There's no mention of it in `npm publish` cli command [docs](https://docs.npmjs.com/cli/v7/commands/npm-publish)

**Comment by mpetuska** [comment]
@albert361 any comments or should I close this for now?

**Comment by mpetuska** [comment]
Closing tgis for now until someone can provide some npm documentation for this.
