### ISSUE TITLE
Could not resolve all artifacts for configuration ':classpath'.

### ISSUE THREAD

**Issue by ConstantinCezB** [mpetuska/npm-publish#15]
> Could not resolve dev.petuska:npm-publish:2.0.1.
     Required by:
         project : > dev.petuska.npm.publish:dev.petuska.npm.publish.gradle.plugin:2.0.1
      > No matching variant of dev.petuska:npm-publish:2.0.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.0.2' but:
          - Variant 'apiElements' capability dev.petuska:npm-publish:2.0.1 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0.2')
          - Variant 'javadocElements' capability dev.petuska:npm-publish:2.0.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0.2')
          - Variant 'runtimeElements' capability dev.petuska:npm-publish:2.0.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0.2')
          - Variant 'sourcesElements' capability dev.petuska:npm-publish:2.0.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0.2')

**Comment by ConstantinCezB** [comment]
I am using kotlin 1.5 and also the new gradle I don't see what could be the problem (read the other post).

**Comment by mpetuska** [comment]
Ah, as the error states, the plugin requires JDK 11+. Is that a deal breaker for you? I might try publishing it for 1.8 ir really pushed.

**Comment by ConstantinCezB** [comment]
No worries, not a deal breaker. Thank you just updated my jdk. (would just be a nice to have) Thanks!
