### ISSUE TITLE
Could not determine the dependencies of task ':assembleJsPackage'

### ISSUE THREAD

**Issue by MichaelOliveiraBx** [mpetuska/npm-publish#159]
Hi 
Thanks for this pluging :) 
I have a problem when I execute the command: `assembleJsPackage`
I have the following error
`"Could not determine the dependencies of task ':assembleJsPackage'."`
I created a project little as possible, here is the stack
- version: **3.4.2**
- kotlin multiplatform: **1.9.22**
- gradle: **8.5**

and here is my build.gradle.kts

```
plugins {
    kotlin("multiplatform") version "1.9.22"
    id("dev.petuska.npm.publish") version "3.4.2"
}

group = "me.michael"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

npmPublish {
    registries {
        register("npmjs") {
            uri.set(uri("--")) //
            authToken.set("obfuscated")
        }
    }
}


kotlin {
    js {
        binaries.executable()
        nodejs {

        }
    }
}
```

If I can help you find don't hesitate :)

**Comment by mpetuska** [comment]
Few things that come to mind:
- Use binaries.library() instead of executable.
- Ensure you have at least one source file
- Check gradle task graph to see what tasks get registered `./gradlew tasks`

**Comment by mpetuska** [comment]
Also you can use npmjs dsl shortcut to register central npm registry (it only needs the token configuration)

**Comment by MichaelOliveiraBx** [comment]
Thanks the issue is with the binaries.library()
My bad and thanks for your reactivity :)
