### ISSUE TITLE
How to include extra files in the package when using Kotlin 2.0?

### ISSUE THREAD

**Issue by YarnSphere** [mpetuska/npm-publish#173]
In a Kotlin Multiplatform project, prior to upgrading to Kotlin 2.0 (i.e. using Kotlin up to 1.9.23) the following worked fine:

```kotlin
npmPublish {
    packages {
        named("js") {
            packageName = "my-package"
            files = files(files + "dir/from/where/to/include/extra/files")
        }
    }
}
```

After the upgrade, however, it fails with:
```
Querying the mapped value of flatmap(provider(?)) before task ':my-project:compileProductionLibraryKotlinJs' has completed is not supported
```

For the time being, I'm including the extra files via a separate copy task which finalizes the `:assembleJsPackage` task.

If the above is meant to not work, would it make sense to also support an `extraFiles` property or similar?

Thank you in advance!

**Comment by mpetuska** [comment]
Your configuration should definitely work, this is a big with k2. Thanks for the report, I'll try to find some time to look into it.

**Comment by mpetuska** [comment]
Oh wait, you're using files property to compute new files property ending up in recursive resolution. Can you try using files.from() instead to append to it?

**Comment by YarnSphere** [comment]
I'm not sure what exactly you want me to try, but I think you simply cannot list the "current files" within the configuration.

For example, this produces the same error:
```kotlin
npmPublish {
    packages {
        named("js") {
            packageName = "my-package"
            files.forEach { println(it.name) }
        }
    }
}
```

**Comment by YarnSphere** [comment]
Oh, simply doing:

```kotlin
files.from("dir/from/where/to/include/extra/files")
```

seems to work, I hadn't realised that `from` works as an append here. Thank you, this is enough for me.

**Comment by YarnSphere** [comment]
I'm unsure how the Kotlin update to 2.0 changed this behaviour, since the code I initially posted was working; but oh well, this is good enough for me. Thank you!

**Comment by mpetuska** [comment]
K2 probably removed some code smells from KGP which surfaced the error you've observed. In any case, `files = files(files + "path")` is not a correct way to append file collection in gradle as this forces eager resolution.
