### ISSUE TITLE
Gradle 8.12 breaks private methods annotated with @TaskAction

### ISSUE THREAD

**Issue by icepuma** [mpetuska/npm-publish#177]
Starting with Gradle 8.12 methods like [NpmAssembleTask::action](https://github.com/mpetuska/npm-publish/blob/master/npm-publish-gradle-plugin/src/main/kotlin/task/NpmAssembleTask.kt#L92-L94) aren't "valid" anymore, due to https://docs.gradle.org/current/userguide/validation_problems.html#private_method_must_not_be_annotated

We get
```shell
org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':assembleApiSpecPackage' (type 'NpmAssembleTask').
  - Method 'action' is private and annotated with @TaskAction.
    
    Reason: Annotations on private methods are ignored.
    
    Possible solutions:
      1. Make the method public.
      2. Annotate the public version of the method.
    
    For more information, please refer to https://docs.gradle.org/8.12/userguide/validation_problems.html#private_method_must_not_be_annotated in the Gradle documentation.
```

when using `id("dev.petuska.npm.publish") version "3.5.0"`

**Comment by DanySK** [comment]
I am also affected. Build scan:  https://gradle.com/s/ofgks5szfo7no

**Comment by mpetuska** [comment]
[3.5.1](https://github.com/mpetuska/npm-publish/releases/tag/3.5.1) Is building with the fix. Thanks for the report.
