### ISSUE TITLE
package.json file template content should be merged not overwrite content

### ISSUE THREAD

**Issue by Sorceror** [mpetuska/npm-publish#29]
Honestly, I'm not sure if this is an issue or its intended behavior, but it should be either fixed or properly noted in the docs.
  
I'm using the `packageJsonTemplateFile` configuration that points to a specific template file (I had a hard time configuring some parts of the plugin in Gradle Groovy syntax).
  
By accident, this ended up in the template file as well.
```
  "dependencies": {
     "@js-joda/core": "3.2.0"
  }
```
and because the code `put`s all values from the file over generated values 
```
publication.packageJsonTemplateFile?.let {
    val template = gson.fromJson(it.readText(), PackageJson::class.java)
    putAll(template) <------
}
```
and I had other dependencies configured correctly in a regular `build.gradle` file, only the dependency from the template file ended in the final `package.json`.

This behavior can occur with other `package.json` values that are objects and not primitives, hence I'm not sure if the content should be rather merged instead of simply overwritten by the content of the template file.

Thanks for keeping this plugin alive and kicking 👍 .

**Comment by mpetuska** [comment]
Hey, thanks for the report!

Merging is certainly preferred, however I simply hadn't got the time to implement it properly (hence the rudimentary override behaviour). 

If anyone wants to give this a go I'd welcome the pr. Otherwise this will have to wait a but until I get a chance to sit down with it.
