### ISSUE TITLE
Unable to load class 'org.gradle.util.internal.GUtil'.

### ISSUE THREAD

**Issue by boldijar** [mpetuska/npm-publish#31]
I'm trying to import this plugin

I'm getting this error

Unable to load class 'org.gradle.util.internal.GUtil'.

This is an unexpected error. Please file a bug containing the idea.log file.

full stracktrace - https://gist.github.com/boldijar/a3c8b3837811bd9d535e8a6256810ab5

shared build.gradle :
```
plugins {
    id("dev.petuska.npm.publish") version "2.1.1"
    kotlin("multiplatform")
    kotlin("plugin.serialization") version "1.6.10"
    id("com.android.library")
    id("com.apollographql.apollo3")
    id("com.chromaticnoise.multiplatform-swiftpackage") version "2.0.3"
}
```

The JS build config
```
  // build for JS
    js(IR) {
        binaries.library()
        nodejs()
    }

```

Root build.gradle
```
buildscript {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
        classpath("com.android.tools.build:gradle:7.0.4")
        classpath("com.apollographql.apollo3:apollo-gradle-plugin:3.0.0")
    }
}
```

I've tried using older gotlin gradle plugin like 1.5.30 and I get the same issue

**Comment by gciatto-unibo** [comment]
What's the version of Gradle again?
 
Also, `"com.android.tools.build:gradle:7.0.4"` may be a source of issues IMHO, as it may be incompatible with Kt > `1.6.x`, if I well remember

**Comment by mpetuska** [comment]
@boldijar unfortunatelly I couldn't reproduce the issue with the following tooling versions:
* Gradle 7.3.3
* Kotlin 1.6.10
* AGP 4.2.2

My suspicion is that you might be using a very old gradle version. Can you try bumping that up and let me know how it goes. If it still doesn't work, at least list out all the relevant tooling versions.

**Comment by mpetuska** [comment]
However looks like GUtil is part of intenal gradle API and shouldn't really be used. To be safe, I've removed all usages of it.
