### ISSUE TITLE
Task are not registered in gradlew

### ISSUE THREAD

**Issue by mihai1voicescu** [mpetuska/npm-publish#39]
I created a sample project to try this out. Although I did the setup the gradle tasks do not seem to be registered and I can't figure out why...

As far as I can tell my config should be supported:
```
vulcan:npm-publish-test mihaivo$ ./gradlew --version

------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.8 (GraalVM Community 11.0.8+10-jvmci-20.2-b03)
OS:           Mac OS X 10.16 x86_64
```

Yet when I try to run the tasks they are not registered.
```
vulcan:npm-publish-test mihaivo$ ./gradlew assembleJsNpmPublication
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.


FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleJsNpmPublication' not found in root project 'npm-publish-test'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
vulcan:npm-publish-test mihaivo$ ./gradlew publishJsNpmPublicationToNpmjs

> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.


FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishJsNpmPublicationToNpmjs' not found in root project 'npm-publish-test'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```
My build file is this:
```
plugins {
    id("dev.petuska.npm.publish") version "2.1.2"
    kotlin("multiplatform") version "1.6.10"
}

group = "io.almer"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

kotlin {
    // Legacy mode
    js(LEGACY) {
        browser() // or nodejs()
    }

    sourceSets {
        val commonMain by getting
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }
        val jsMain by getting
        val jsTest by getting
    }
}

npmPublishing {
    repositories {
        repository("npmjs") {
            registry = uri("https://registry.npmjs.org")
            authToken = "asdf"
        }
    }
}
```
I also attached an [Archive.zip](https://github.com/mpetuska/npm-publish/files/8387618/Archive.zip) with the project.

**Comment by mihai1voicescu** [comment]
The problem seems to be the plugin does not automatically detect publications from MPP, as stated in the README.

**Comment by mpetuska** [comment]
Can you try with IR js backend? Legacy backend support has been an afterthought for quite a few releases.

**Comment by mpetuska** [comment]
OK, I've finally had a chance to look into your sample project and found the issue. The publications are not generated because your project does not have any JS outputs due to `kotlin.js.generate.executable.default=false` gradle property. Removing that from `gradle.properties` or setting it to true (default value) will unlock JS publications autoconfigured by this plugin.  This is expected behaviour for the plugin as it aims to be non-intrusive and only register tasks when it's appropriate to do so.

Can you please try it out and let me know if I can close this issue.

**Comment by mihai1voicescu** [comment]
Thank you for your help!

Adding `kotlin.js.generate.executable.default=false` did indeed fix the problem and allow me to publish.

As a side note maybe you should also add a one-time sponsorship option on Github (if it's possible, I don't really know). Apparently, companies hate recurring fees and the sending fee on Paypal is a joke.

**Comment by mpetuska** [comment]
Hmm, I don't think GH supports one-time sponsorships so PayPal was the only option for that I could think of :laughing:

**Comment by mpetuska** [comment]
Scratch that. GH Sponsors now support one-off payments and custom ammounts. I've enabled both now.

Thanks for bringing this up to my attention.
