### ISSUE TITLE
Compatibility with maven publications for both 'legacy' and 'ir' JS backends

### ISSUE THREAD

**Issue by fullkomnun** [mpetuska/npm-publish#4]
JetBrains has [suggested](https://kotlinlang.org/docs/js-ir-compiler.html#authoring-libraries-for-the-ir-compiler-with-backwards-compatibility) that library maintainers who wish to offer support for the 'IR' backend while keeping support for the 'legacy'(default) JAS compiler backend use the following config:
```kotlin
kotlin {
    js(BOTH) {
        // . . .
    }
}
```

So `maven-publish` gradle plugin publishes both `jar` and `klib` artifacts under the same target.
How would you suggest to transform this config to use `npm-publish` while keeping this backwards-compatible setup?
Is there a way to do so without adding an additional JS custom target with a specific `KotlinJsCompilerType`?

**Comment by mpetuska** [comment]
The plugin should automatically configure npmPublications for both, IR and Legacy artefacts. In any case, regardless of the KotlinJS backend, you're publishing JS output to npm, so either of those essentially achieve the same NPM package. No need to publish both to NPM.
