### ISSUE TITLE
Gradle Propertly CLI Overrides Not Working

### ISSUE THREAD

**Issue by davidtaylor-juul** [mpetuska/npm-publish#48]
Overriding grade properties via the CLI does not appear to be working. In our case we were overriding the version and the auth token for publishing to GitHub, which was working in v2.x:

```
// for v2.x (was working)
-Pnpm.publish.repository.github.authToken="<redacted>"
-Pnpm.publish.version="0.0.1"

// gradle
npmPublishing {
  repositories {
         repository("github") {
             access = RESTRICTED
             registry = uri("https://npm.pkg.github.com")
             authToken = "notarealtoken"
             version = "0.0.1-placeholderversion1"
        }
  }
}
```

For v3.x neither of these CLI overrides are working anymore (we swapped `repository` for `registry` according to  https://npm-publish.petuska.dev/3.0/user-guide/configuration/registry/) :

```
// for v3.x (not working)
-Pnpm.publish.registry.github.authToken ="<redacted>"
-Pnpm.publish.version="0.0.1"

// gradle
npmPublish {
    version.set("0.0.1-placeholderversion1")
    registries {
        github {
            access.set(RESTRICTED)
            uri.set(uri("https://npm.pkg.github.com"))
            authToken.set("notarealtoken")
        }
    }
}
```

Neither of these CLI properties are applied when building the NPM package.

**Comment by mpetuska** [comment]
As per the docs:

> The layering only works for properties that have no explicit values set via the DSL as doing so overrides any layering or default behaviour.

So this is working as intended. If you wish to maintain some default value which you then override from the cli, may I suggest using gradle.properties file for that?

**Comment by mpetuska** [comment]
Here's the setup you need to unlock cli overrides
```kotlin
npmPublish {
    registries {
        github {
            access.set(RESTRICTED)
        }
    }
}
```

I've also removed explicit URI as github registry shortcut already sets that for you.

**Comment by mpetuska** [comment]
Thanks for letting me know
