### ISSUE TITLE
Empty package (no executables)

### ISSUE THREAD

**Issue by MarcinMoskala** [mpetuska/npm-publish#54]
In the following project:
https://github.com/MarcinMoskala/AnkiMarkdown

When I push a package to NPM, it seems empty. No binary code. I do export a single class:
https://github.com/MarcinMoskala/AnkiMarkdown/blob/master/src/jsMain/kotlin/AnkiConnectorJs.kt

In the build/packages/js I have all the files I need. They are just not included in the final package. 

<img width="224" alt="image" src="https://user-images.githubusercontent.com/6850787/179344687-2b6f69b7-24b0-42e8-892d-2c0cb67ff938.png">

**Comment by mpetuska** [comment]
You register a new package and do not attach any files to it. The plugin autoconfugures packages for all js targets if detected, so instead of registering a new package, try named("js") {}

**Comment by mpetuska** [comment]
I'm closing this as it seems to be a misunderstanding rather than a bug. Feel free to continue the conversation here anyways if you still need help.

**Comment by MarcinMoskala** [comment]
I changed the name from "js", due to the following error:

Build file '/Users/marcinmoskala/Projekty/AnkiMarkdown/build.gradle.kts' line: 77

Cannot add a NpmPackage with name 'js' as a NpmPackage with that name already exists.

**Comment by mpetuska** [comment]
You changed the name, but not the function. Just remove your packages block and it should work just fine

**Comment by MarcinMoskala** [comment]
Without packages, how can I change `packageName`? In general, how can I configure this package?

When I changed to that:

```
npmPublish {
    registries {
        register("npmjs") {
            uri.set(uri("https://registry.npmjs.org")) //
            authToken.set(properties["npmSecret"] as String)
        }
    }
}
```

The problem is that the package name is AnkiMarkdown, not ankimarkdown as it should be.

**Comment by mpetuska** [comment]
Ah, then instead of using register("pkgName"){} use named("pkgName") {} to configure an existing package instead of creating it.

**Comment by MarcinMoskala** [comment]
Perfect, that works, thank you :)

**Comment by mpetuska** [comment]
Glad you got it working in the end. Pro tip, you can use npmjs() registry shortcut for more concise setup
