### ISSUE TITLE
Gradle submodule NPM dependency not added to generated package.json resulting in missing module errors

### ISSUE THREAD

**Issue by gchristov** [mpetuska/npm-publish#65]
I have a multi-module Gradle setup for KotlinJS with main `appJs` and `submodule` definitions below, which correctly generates the `package.json` with the `node-html-parser` dependency file under `/build/productionLibrary`. This makes it available to the submodule when I run `npm install` as it appears under the resulting `node_modules`.
```
// appJs/build.gradle

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("dev.petuska.npm.publish")
}
kotlin {
    js(IR) {
        nodejs()
        binaries.library()
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(npm("node-html-parser", "6.1.4"))
                implementation(projects.submodule)
            }
        }
    }
}
```

```
// submodule/build.gradle

plugins {
    id("org.jetbrains.kotlin.multiplatform")
}
kotlin {
    js(IR) {
        nodejs()
    }
}
```

However, when I move the ` implementation(npm("node-html-parser", "6.1.4"))` dependency to the submodule, I get `Error: Cannot find module 'node-html-parser'`.

As discussed on Slack, this appears to not be supported yet by the `npm-publish` plugin and would be a nice improvement to have if possible. Thanks! 🙇 

### Workaround

As a workaround, I can list all `npm` dependencies under the main `appJs` module which makes them available to all submodules.

**Comment by gchristov** [comment]
@mpetuska I updated to the latest version and gave this another go by moving one of my `npm` dependencies from my main `app` module (where the plugin is applied, to a submodule but it's still not present in the final `package.json` file. 

Is there any extra configuration needed somewhere? My setup is as before.

**Comment by mpetuska** [comment]
Which kotlin version are you on?

**Comment by gchristov** [comment]
`1.7.20` and I updated the plugin to version `3.2.0`

**Comment by mpetuska** [comment]
Ah, you need kotlin 1.8+ to get the fix. Can you try upgrading and let me know if it works for you?

**Comment by gchristov** [comment]
Hmm same with Kotlin version `1.8.10`. I upgrade my project as well as Gradle to `7.6`. Do you have a working example perhaps?

**Comment by mpetuska** [comment]
Finally had a chance to look at it. Looks like a kotlin plugin issue since npm-plugin merges `build/tmp/publicPackageJson/package.json` dependencies that are generated by the kotlin plugin. Can you check your publicPackageJson (generated by kotlin plugin) to verify that the transitive dependencies are missing on your end too?

Closing this for now, but feel free to reopen if you can prove me wrong.

**Comment by gchristov** [comment]
Thanks will find time to have a look!
