### ISSUE TITLE
packages.named("js"): NpmPackage with name 'js' not found

### ISSUE THREAD

**Issue by marco-eckstein** [mpetuska/npm-publish#75]
The plugin saves the package files to the folder `build/packages/js/`, but when I try to customize the package, I get the error _NpmPackage with name 'js' not found._

```kotlin
npmPublish {
    // ...
    packages {
        named("js") {
            packageJson {
                "customField" by true
            }
        }
    }
}
```

So what's the name of the package then?

Plugin version 3.1.0.

**Comment by mpetuska** [comment]
The name of autoconfigured package is the same as your kotlin target (default is "js" if you don't specify it explicitly). To assist more i need to know your kotlin version and inspect gradle buildfile.

**Comment by marco-eckstein** [comment]
You can reproduce the issue with https://github.com/marco-eckstein/kotlin-lib/tree/mpetuska-npm-publish-issue-75. As it is, it builds fine. You need to toggle the comment around the `named("js")` section.

**Comment by mpetuska** [comment]
Thanks!

**Comment by mpetuska** [comment]
At first glance I suspect it's a race condition seeing as your npmPublish block is above kotlin block. Should be fixed regardless.

**Comment by marco-eckstein** [comment]
Switching the order fixes the issue indeed. Thanks for the quick help!

**Comment by mpetuska** [comment]
Unfortunately there's nothing that can be done to improve this with the current state of gradle's lazy loading. Closing this issue for now.
