### ISSUE TITLE
`kotlin.js.compiler=ir` in `gradle.properties` required

### ISSUE THREAD

**Issue by ChristianKatzmann** [mpetuska/npm-publish#95]
# Reproducer: [ChristianKatzmann/npm_publish_legacy_ir](https://github.com/ChristianKatzmann/npm_publish_legacy_ir)

### [`org.jetbrains.kotlin.js` with `dev.petuska.npm.publish`](https://github.com/ChristianKatzmann/npm_publish_legacy_ir/commit/bf9e7adc31d2e08b0d4ed41285b06d6541f9ad2f)
If I apply the `dev.petuska.npm.publish` plugin in version `3.2.0` to an `org.jetbrains.kotlin.js` plugin in version `1.8.0` with `js(IR)` configured, I run in the following exception:

```
This project currently uses the Kotlin/JS Legacy compiler backend, which has been deprecated and will be removed in a future release.
Please migrate the project to the new IR-based compiler (https://kotl.in/jsir) by adding:
- kotlin.js.compiler=ir to your gradle.properties file.
- js(IR) { ... } to your build file.
You can continue to use the deprecated legacy compiler in the current version of the toolchain by specifying it explicitly.
```

### [`kotlin.js.compiler=ir` via `gradle.properties`](https://github.com/ChristianKatzmann/npm_publish_legacy_ir/commit/09adc93752eff2353c5d218b07e142a75051e69c)
By adding the `kotlin.js.compiler=ir` line to `gradle.properties` the `build` succeeds.

### [Remove `dev.petuska.npm.publish` and revert `gradle.properties`](https://github.com/ChristianKatzmann/npm_publish_legacy_ir/commit/e9111c19671da861d184b0d96c9b7529ed94c077)
If I disable the `dev.petuska.npm.publish` plugin and revert `gradle.properties` the `build` succeeds without any warning.

**Comment by mpetuska** [comment]
This is a known limitation of KJS plugin when it comes to setting compiler mode in the DSL. I'm not really sure why the plugin surfaces it since it's autoconfiguring after kjs plugin. Might be worth raising an issue for this on kotlin repo instead (looks like they're evaluating that check too early).
